regions:
    lab:
        endpoint: ENC[AES256_GCM,data:YWVV2BfSnfGn,iv:iEeyaajHznMIfz0wF5JNDA5AmyqlJmj9Q65W8h5rcyM=,tag:ksTCX+xOdUb9KsOmfYjjYQ==,type:str]
        username: ENC[AES256_GCM,data:YzfaO5I5n+g=,iv:HJNb3kKXjOBktvRkFUwnBDY28XB301CHIdm+fzenzNg=,tag:pqaq0zZGNoeU7UW6gCjBug==,type:str]
        password: ENC[AES256_GCM,data:RJwtEYSnX84=,iv:/9f9r2CZSqr3iNgs6hR2cDb2a6eoRuSpP5QUzLJk7Fg=,tag:9Ql6SHmVhjmEqyddank2JA==,type:str]
identity:
    vmc_dev:
        username: ENC[AES256_GCM,data:30jR4HJK,iv:i4uc351QNiP1aUN0uyRs9yVg68NpjO7p4igXib0OW2s=,tag:WrEFmiVkX+j0v3qghYUmVg==,type:str]
        password: ENC[AES256_GCM,data:1AiWz1WQuJAoLvT/,iv:mkVEm0CBlXYnUVqOxBZMaFpCflTTLKIBkCZnty8W89s=,tag:w/LEMeksZ836RzH+F3bAYQ==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-east-2:665846930766:alias/vdo/rpcv/api/prod
        created_at: '2020-02-21T21:38:05Z'
        enc: AQICAHgMaA445A+3qkSH6FRaKo9EkVtR8KQH3UwxNTbsvGWZywF6yDSw8nGcfl0XMGPLn+qEAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMmMUkYRIelZhs3e+rAgEQgDt1g60ItnpYx/92Gikbvv3/1Iyq3GA4x2lmsJTQXvDlnFb3tU846EgJZ/TP0z1wGMDSMEUfOLKfD5tEuA==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-04-13T20:35:40Z'
    mac: ENC[AES256_GCM,data:M3jHf5Z7QmeVsD+UG+AEWWX2OHkLU80SZA7cAcHPICgnGW43q0MF0FA3GHsTZgSeIGIny/f4gBVH8y/wic+Ssp8DN+cSUxMlA/79G0orhNHrpzH8M96SOyGTltWJuC37wrNFx4+8/z6LHTKYNPIUo/EMyilMqxZndi4gVpY1xK0=,iv:z0IhKSC7K02eyzAtaOkVSe7zlHXbbHvZATpdVTpPHik=,tag:9+uQ8Q0Icv5h3elliBjNUA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.5.0
