#!/usr/bin/env bash

set -e

log () {
  echo -e "\e[1m==> $@\e[0m"
}

error () {
  echo -e "\e[31;1m$@\e[0m"
}

if [[ $# -lt 1 ]]; then
  echo "Usage: scripts/bootstrap-terraform <environment>"
  echo ""
  error "scripts/bootstrap-terraform requires an environment to be provided."
  exit 1
fi

ENVIRONMENT=$1
BUCKET="vdo-ops-terraform-state-${ENVIRONMENT}"

if ! aws s3api head-bucket --bucket "$BUCKET" >/dev/null 2>&1
then
  log "Terraform state file S3 bucket ${BUCKET} does not exist."
  log "Creating s3://${BUCKET} in ${AWS_REGION}..."

  if ! aws s3 mb s3://"$BUCKET" --region "$AWS_REGION"
  then
    error "Error creating s3://${BUCKET}. Exiting."
    exit 1
  fi

  log "Enabling versioning for s3://${BUCKET}"
  aws s3api put-bucket-versioning --bucket ${BUCKET} --versioning-configuration Status=Enabled
else
  log "Terraform state file S3 bucket ${BUCKET} exists."
fi
